### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by suhao** [walklang/flutter#1]
###### flutter, doctor

本文记录了个人在flutter使用中的各种问题，以及相关解决方法。

# 一、windows下搭建Flutter环境

本地环境：
* windows10 企业预览版
* java1.8
* git

我按照flutter官网的教程，进行环境的搭建和测试，大家可以访问[https://flutter.dev/docs/get-started/install/windows](https://flutter.dev/docs/get-started/install/windows)，然后参考本文来规避各种可能的坑。
## 基础环境配置

1. JAVA配置

下载按照java 1.8版本，然后配置JAVA_HOME变量，如：
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_201

在PATH环境变量中，增加jdk的相关配置：
```
C:\Program Files\Java\jdk1.8.0_201\bin;
C:\Program Files\Java\jdk1.8.0_201\lib;
C:\Program Files\Java\jre1.8.0_201\bin;
C:\Program Files\Java\jre1.8.0_201\lib;
```

2. Gradle配置

下载安装gradle的最新版本，然后添加GRADLE_HOME，如：
GRADLE_HOME = D:\shells\env\gradle\gradle-5.2.1

PATH环境变量中，添加%GRADLE_HOME%\bin

## 安装AndroidStudio

从官网安装Android studio，然后根据向导安装AndroidSDK

1. 配置环境变量
```
ANDROID_HOME = C:\Users\suhao\AndroidSDK
PATH = %PATH%; C:\Users\suhao\AndroidSDK\platform-tools\; C:\Users\suhao\AndroidSDK\platforms; C:\Users\suhao\AndroidSDK\tools\; C:\Users\suhao\AndroidSDK\tools\bin\; C:\Program Files\Android\Android Studio\jre\bin; C:\Program Files\Android\Android Studio\jre\lib; C:\Program Files\Android\Android Studio\jre\jre\bin; C:\Program Files\Android\Android Studio\jre\jre\lib
```
2. 下载flutter和dart插件

3. 更新系统的Hyper-X支持： 通过windows feature添加即可，可能需要修改bios，根据各自的电脑进行修改

4. 创建Android虚拟机：按照向导创建，原则上不用修改即可。我电脑上必须将vscode或者Androidstudio以管理员权限打开才能正常启动虚拟机模拟器

## 安装flutter
1. 按照官网介绍，安装最新的flutter版本： 我将各个软件和sdk统一在D:\shells下，可以参考https://github.com/suhao/shells

2. 配置环境变量：在path环境变量中添加D:\shells\framework\flutter\bin\

3. 根据需要，如果国内网络可以访问就不用配置mirror，反之参考官网配置下china的host

4. 执行命令：flutter doctor，如果运行未出现错误，那么恭喜你环境配置成功了

5. 打开Androidstudio，按照向导创建flutter工程，然后点击run，马上就可以在Android模拟器上看到我们的第一个flutter应用程序界面了

## 安装vscode
使用Androidstudio会消耗大量的系统资源，在个人电脑上运行太卡。转战vscode，更加轻便。
关于vscode的使用，请自行搜索。
1. 安装flutter 和 dart插件
2. 向导生成flutter工程，点击run运行

## 那些遇到的坑和解决方法
1. [doctor无法找到AndroidSDK](https://github.com/suhao/flutter/issues/1#issuecomment-481129076)
2. [doctor无连接设备](https://github.com/suhao/flutter/issues/1#issuecomment-481129106)
3. [Android toolchain出现感叹号](https://github.com/suhao/flutter/issues/1#issuecomment-481129150)
4. [模拟器无法启动](https://github.com/suhao/flutter/issues/1#issuecomment-481129183)
5. [doctor需要确认license，执行命令后提示sdk需要更新，sdk更新失败](https://github.com/suhao/flutter/issues/1#issuecomment-481129203)
6. [gradle无法重用daemons](https://github.com/suhao/flutter/issues/1#issuecomment-481129237)
7. [执行run后出现异常：out of memory，显卡异常，vscode/cmd/Androidstudio崩溃](https://github.com/suhao/flutter/issues/1#issuecomment-481129262)

**Comment by suhao** [comment]
## 操作说明

执行 **flutter doctor**，提示Android SDK路径不对
 
## 错误信息
X ANDROID_HOME = D:\shells\SDK\Android, but Android SDK not found at this location
## 解决方案 
1. 在环境变量中添加SDK目录下的platform-tools、platforms、tools、tools\bin路径配置
2. 重启Power Shell, 再次运行flutter doctor

## 我是黑板
tools\bin路径需要注意，尝试了很久发现这个路径在windows10上需要配置后方正常运行

**Comment by suhao** [comment]
## 操作说明

执行 **flutter doctor**，提示连接设备无有效设备
 
## 错误信息
Connected device, ! No devices available
## 解决方案 
1. 执行 _fluter emulators_ , 查看是否有创建完成的模拟器，并按照提示launch指定的设备
2. 重启Power Shell, 再次运行flutter doctor

## 我是黑板
1. 如果有设备直接执行命令launch，如果无设备需要打开Android Studio的AVD Manager添加模拟器
2. 模拟器启动会出现Process finished with exit code 1(Android Studio左下角的状态栏，不要错过提示信息哦)，此时检查SDK manager的SDK tools是否未安装Intel x86 Emulator Accelerator(为了规避错误，我安装了所有的工具选项)，安装它再启动模拟设备
3. 虚拟机建议创建为Nexus 5 API 28，4.95 1080*1920xxhdpi，Pie：Android 9.0 x86

**Comment by suhao** [comment]
## 操作说明

执行 **flutter doctor**，提示Android toolchain黄色感叹号
 
## 错误信息
[!]android toolchain - develop for android devices (android sdk 28.0.3)
## 解决方案 
1. 运行**flutter doctor --android-licenses**命令
2. 一路**y+Enter**

## 我是黑板
执行了**flutter doctor -v**，没有发现异常，上次安装出现过licenses的问题，试了一下果然是这样

**Comment by suhao** [comment]
# 操作说明
Android Studio安装在C盘默认位置，创建完模拟器后，执行启动失败
# 错误信息
13:23	Emulator: C:\Users\suhao\AndroidSDK\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: WHPX: Failed to create partition, hr=80070005
13:23	Emulator: C:\Users\suhao\AndroidSDK\emulator\qemu\windows-x86_64\qemu-system-x86_64.exe: failed to initialize WHPX: Invalid argument
# 解决方案
尝试了N多方法，google出来的很多方案均不能生效。突然想起来安装在C盘会否是权限问题？
最终使用管理员模式启动Android Studio，启动成功了，就这样成功了。。。。。。

# 我是黑板
如果执行doctor命令没有错误，执行各种操作均无问题，考虑下使用管理员权限模式吧，虽然不喜欢这种方式，但是确实解决了很多莫名其妙的异常

**Comment by suhao** [comment]
# 操作说明
执行doctor命令，提示license未知，然后需要更新sdk，但是更新失败
# 错误信息
```
$ flutter doctor -v
✗ Android license status unknown
$ flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
tools/bin/sdkmanager --update
$ sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 5 more
```
# 我是黑板
1. 百度+google尝试了各种办法，例如修改sdkmanager脚本等均无效(如修改脚本：https://blog.laji.cx/post/deal-with-android-sdkmanager-update-error/)。

# 解决方案
1. 访问[Java官网下载jdk8版本](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)
2. 下载后安装，配置JAVA_HOME路径，指向1.8版本路径
3. 重启Android studio和cmd，执行flutter doctor -v

**Comment by suhao** [comment]
# 操作说明
执行flutter run操作后提示gradle无法use Daemons

# 尝试操作
1. 添加环境变量%GRADLE_HOME%
2. path环境变量添加%GRADLE_HOME%\bin，%GRADLE_HOME%\lib
3. 执行如下命令
```
$ gradle --status
确认是否又Daemons已经运行
$ cd %ProjectPath%\android
$ gradlew
创建Daemons
```

**Comment by suhao** [comment]
# 操作和现象说明
执行flutter run出现vscode/AndroidStudio/cmd崩溃，系统显卡出现异常(例如屏幕分辨率变化了、双屏突然只能识别一个)，个人的原因为显卡或者其他驱动出现了问题(其他人是否遇到？是否都是这个原因？不得而知)

# 解决办法
1. 更新显卡驱动和各个设备的驱动
2. cmd命令行执行flutter run，确认是否能够正常运行
3. 系统是否关闭了虚拟内存？磁盘虚拟内存打开后各种异常就自动消失了
